"""empty message

Revision ID: 247815cc7413
Revises: b6b2bb35e1fb
Create Date: 2024-12-17 11:41:16.378005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247815cc7413'
down_revision = 'b6b2bb35e1fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('igdb_url', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('release_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('release_year')
        batch_op.drop_column('image_url')
        batch_op.drop_column('igdb_url')

    # ### end Alembic commands ###
