"""played games

Revision ID: b6b2bb35e1fb
Revises: f2d36c2799de
Create Date: 2024-12-16 22:41:32.931299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b2bb35e1fb'
down_revision = 'f2d36c2799de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('played_games',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_favorite_game')
        batch_op.drop_column('favorite_game')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_game', sa.VARCHAR(length=120), nullable=True))
        batch_op.create_index('ix_user_favorite_game', ['favorite_game'], unique=1)

    op.drop_table('played_games')
    op.drop_table('game')
    # ### end Alembic commands ###
