"""empty message

Revision ID: c695aca51348
Revises: cc5ffcc5af73
Create Date: 2024-12-17 15:12:17.163248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c695aca51348'
down_revision = 'cc5ffcc5af73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('igdb_url', sa.VARCHAR(length=256), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=256), nullable=False),
    sa.Column('release_year', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
