"""empty message

Revision ID: e8e0be67a20a
Revises: 510eac0265cd
Create Date: 2024-12-19 21:26:36.513598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e0be67a20a'
down_revision = '510eac0265cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('hours_played', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_play_game_id_game')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_play_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'game_id', name=op.f('pk_play'))
    )
    op.drop_table('played_games')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('played_games',
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    op.drop_table('play')
    # ### end Alembic commands ###
