"""empty message

Revision ID: f2d36c2799de
Revises: 7d3005cce5a5
Create Date: 2024-12-16 12:14:31.456709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d36c2799de'
down_revision = '7d3005cce5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_game', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_favorite_game'), ['favorite_game'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_favorite_game'))
        batch_op.drop_column('favorite_game')

    # ### end Alembic commands ###
